### ISSUE TITLE
[Feature Request] Windows OS Version

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/ever2boost#5]
Hello, thanks for the CLI Tool.
How to run it on Windows?
Do we only need to install [Ruby](https://rubyinstaller.org/downloads/) first ?

**Comment by asmsuechan** [comment]
@tatoosh Sorry for my late reply. Yes, you do. You have to install Ruby first.

**Comment by tatoosh** [comment]
@asmsuechan ok no problem, thanks!
